#!/usr/bin/env bash
# Gerado pelo CI (GitHub Actions) em cada push — não execute manualmente.
# Gera version.js (ignorado pelo git) e estampa ?v=<commit> nos módulos JS
# do index.html para forçar cache-bust no browser após cada deploy.
# Uso: ./update-version.sh          (usa o commit atual)
#      ./update-version.sh v0.2     (altera o semver base)
set -euo pipefail

SEMVER="${1:-v0.2}"
COMMIT=$(git rev-parse --short HEAD)
VERSION="${SEMVER}.${COMMIT}"

cat > version.js <<EOF
// Auto-generated by update-version.sh — do not edit manually
window.APP_VERSION = '${VERSION}';
EOF

# Atualiza (ou adiciona) ?v= em todos os módulos js/app-*.js no index.html
sed -i -E "s|(js/app-[^.]+\.js)(\?v=[^\"]*)?\"|\1?v=${COMMIT}\"|g" index.html

echo "Atualizado: ${VERSION}"
