#!/usr/bin/env bash
# Gera version.js e atualiza cache-busting dos módulos JS no index.html.
# Uso: ./update-version.sh          (usa o commit atual)
#      ./update-version.sh v0.2     (altera o semver base)
set -euo pipefail

SEMVER="${1:-v0.1}"
COMMIT=$(git rev-parse --short HEAD)
VERSION="${SEMVER}.${COMMIT}"

cat > version.js <<EOF
// Auto-generated by update-version.sh — do not edit manually
window.APP_VERSION = '${VERSION}';
EOF

# Atualiza (ou adiciona) ?v= em todos os módulos js/app-*.js no index.html
sed -i -E "s|(js/app-[^.]+\.js)(\?v=[^\"]*)?\"|\1?v=${COMMIT}\"|g" index.html

echo "Atualizado: ${VERSION}"
