#!/usr/bin/env bash
# Gera version.js e atualiza cache-busting do app.js no index.html.
# Uso: ./update-version.sh          (usa o commit atual)
#      ./update-version.sh v0.2     (altera o semver base)
set -euo pipefail

SEMVER="${1:-v0.1}"
COMMIT=$(git rev-parse --short HEAD)
VERSION="${SEMVER}.${COMMIT}"

cat > version.js <<EOF
// Auto-generated by update-version.sh — do not edit manually
window.APP_VERSION = '${VERSION}';
EOF

# Atualiza o ?v= no script tag do app.js para forçar reload no browser
sed -i "s|js/app\.js?v=[^\"]*|js/app.js?v=${COMMIT}|g" index.html

echo "Atualizado: ${VERSION}"
